 reference_points:
   - {latitude: 34.0522, longitude: -118.2437, pixel_x: 100, pixel_y: 200}  # Example: Los Angeles City Hall
   - {latitude: 34.0525, longitude: -118.2434, pixel_x: 500, pixel_y: 200}
   - {latitude: 34.0520, longitude: -118.2430, pixel_x: 100, pixel_y: 500}
   - {latitude: 34.0527, longitude: -118.2439, pixel_x: 500, pixel_y: 500}